project:
  type: book

pdf-engine: xelatex

book:
  title: "Greek Reading: Society in Nature"
  author: "Neel Smith"
  date: "2/9/2026"

  chapters:
    - index.qmd
    - strabo-intro.qmd
    - strabo-selection1.qmd
    - dp-intro.qmd
    - dp-selection.qmd
    - dp-all-text.qmd


format:
  html:
    theme: cosmo
    css: styles.css
  pdf: 
    documentclass: scrreprt
    geometry:
      - margin=1in    
    monofont: "Menlo"
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \usepackage{paracol}
    filters:
      - columns-to-latex.lua