project:
  type: book

pdf-engine: xelatex

book:
  title: "Greek Reading: Society in Nature"
  author: "Neel Smith"
  date: "1/19/2026"

  chapters:
    - index.qmd
    - strabo-intro.qmd
    - strabo-selection1.qmd



format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf:
    monofont: "DejaVu Sans Mono"
    mainfont: "Times New Roman"